***NumPy Turtorial***



In [8]:
import numpy as np

a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

***NumPy array example***  
Initalising and printing a NumPy array

In [9]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[0])

[1 2 3 4]


In [10]:
b = np.array([1,3,4,5,6])

In [13]:
b.shape

(5,)

***An array filled with zeros***

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.empty([2])

array([-3.97879600e-71,  1.50550462e+76])